### ISSUE TITLE
Would it be easy/possible to include faster than x2?

### ISSUE THREAD

**Issue by RyanGaudion** [RemLampa/facebook-video-speed-control#18]

**Comment by RemLampa** [comment]
@RyanGaudion Yes, certainly. I'll need someone to get to it though. Can't devote time at the moment.

**Comment by lawdalana** [comment]
@RemLampa Can you review on this PR [https://github.com/RemLampa/facebook-video-speed-control/pull/22](url)

**Comment by RemLampa** [comment]
@RyanGaudion Feature is available now on Chrome Web Store as version 0.2.1!

@lawdalana Thanks so much for your help!
