### ISSUE TITLE
Support the "new Facebook" video player

### ISSUE THREAD

**Issue by Mahmoudz** [RemLampa/facebook-video-speed-control#2]
@RemLampa Thanks for this very useful tool.

It works well with Facebook Classic, but not after switching to the New Facebook UI.

Using latest GoogleChrome on MacBook.

**Comment by RemLampa** [comment]
Submitted the new version in Chrome Web Store. It's still pending approval. Will close this when it gets published. Thanks!

**Comment by RemLampa** [comment]
New version now available on Chrome Web Store.
